### ISSUE TITLE
How to make the heart animation a bit smaller?

### ISSUE THREAD

**Issue by Realife-Brahmin** [maxbennedich/code-golf#1]
I'm trying to incorporate the heart animation in my `startup.jl` file, because it's cute. But right now it is a bit too big for my preferences, and I'd like it be about 40% smaller. Unfortunately, I don't understand the code and the mathematics behind it that well (even though you've explained the code well). Can I get some help regarding that?

**Comment by maxbennedich** [comment]
Hi, sure, it's a bit cryptic :) You would need to change in three places: the size of the buffer, the loop over the pixels, and the scaling. See an example below where I marked the changed lines with `CHANGED`. You can experiment with these numbers to change the size and aspect ratio. If you don't care about the "code golf" aspect, you can of course extract these to constants so that you only have to change in one place. Let me know if you need further help.
```julia
# rotation angle 'd' goes from 0 to 2π (one revolution)
0:2e-3:2π .|> d-> (
    # screen buffer, with empty braille characters and new lines
    (P = fill(5<<11,41,16))[41,:] .= 10;  # <-- CHANGED; buffer size
    # transformation vector: cis = rotation, sin = zoom
    z = 8cis(d)sin(.46d);
    # loop over all pixels
    for r=0:62, c=0:79  # <-- CHANGED; 62 = 16*4-2, 79 = 41*2-3
        # (..)z = scale and rotate point, using complex numbers
        # reim = split complex number into x/y
        # mod = repeat pattern
        x,y = @.mod(2 - $reim((2c/79-r/31im-1-im)z), 4) - 2;  # <-- CHANGED, to match max r and c
        # test if point is within a heart shape
        √2(y+.5-√√x^2)^2 < 4-x^2 &&
            # set pixel, using braille characters
            (P[c÷2+1,r÷4+1] |= Int(")*,h08H¨"[1+r&3+4&4c]) - 40)
    end;
    # print buffer to screen
    print("\e[H\e[1;31m", join(Char.(P))));
```

**Comment by Realife-Brahmin** [comment]
New heart size is perfect for me! Thanks a lot!
